# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# For more information, see https://jekyllrb.com/docs/configuration/

# Site settings
course_name: DS701 Tools for Data Science (tools4ds)
course_description: "This course is a Master’s level introduction to data science, focusing on proficiency in working with and
analyzing data. The course emphasizes practical skills in working with data, while introducing students to a
wide range of techniques that are commonly used in the analysis of data, such as clustering, classification,
regression, and network analysis."

# replace with your course semester and year, e.g. "Spring 2024"
course_semester: "Fall 2024"

# replace with 2 letter semester abbreviation and year, e.g. "sp2024"
baseurl: "/fa2024" # the subpath of your site, e.g. /blog/

# Do not edit unless you are posting to some other github pages site
url: "http://tools4ds.github.io" # the base hostname & protocol for your site

schoolname: "Boston University Faculty for Computing and Data Science"
schoolurl: "https://www.bu.edu/cds-faculty/"

# uncomment to list your contact info
# twitter_username: trgardos 
# google_scholar_id: tY3MyCgAAAAJ
# linkedin_username: thomas-gardos
github_repo: https://github.com/tools4ds/fa2024

address: |
    Boston, MA
    USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true

# End of "Do not change" section

# Jekyll is built around organized collections. See https://jekyllrb.com/docs/collections/
collections:
    events:
        output: true
    lectures:
        output: true
    discussions:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    projects:
        output: true

# You can set default values for collections, for example default layouts.
defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

plugins:
  - jekyll-include-cache
  - gemfile
